version: "3.7"

services:
  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:latest
    container_name: currency-monitor-auth-generator
    environment:
      AUTH_TOKEN_LIFETIME: 2
    networks:
      - currency-monitor-network

  currency-service:
    image: ghcr.io/fedosb/currency-monitor/services/currency:latest
    container_name: currency-monitor-currency-service
    environment:
      # Net config
      GRPC_ADDRESS: ":50051"
      # Currency API config
      CURRENCY_API_URL: "https://latest.currency-api.pages.dev/v1/currencies"
      # DB config
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: currency
      DB_SSL: disable
      DB_MAX_OPEN_CONNECTIONS: 10
      DB_MAX_IDLE_CONNECTIONS: 5
      DB_MAX_CONNECTION_LIFETIME: 5m
      DB_APPLY_MIGRATIONS: "true"
      # Fetcher
      FETCH_INTERVAL: 5s
      REQUEUE_FAILED_JOBS_INTERVAL: 10s
      JOB_RESCHEDULE_INTERVAL: 24h
      FAILED_JOB_RESCHEDULE_INTERVAL: 5m
      FAILED_JOB_MAX_RETRIES: 3
      PROCESS_JOB_MAX_WORKERS: 1
      CURRENCIES: "usd,eur,gbp,algo"
      RUN_IMMEDIATELY: "true"
    networks:
      - currency-monitor-network

  gateway-service:
    image: ghcr.io/fedosb/currency-monitor/services/gateway:latest
    container_name: currency-monitor-gateway-service
    ports:
      - "8081:8081"
    environment:
      # Net config
      HTTP_ADDRESS: ":8081"
      # Auth API
      AUTH_API_URL: "http://auth-generator:8080"
      # Currency service
      CURRENCY_SERVICE_ADDRESS: "currency-service:50051"
    depends_on:
      - currency-service
      - auth-generator
    networks:
      - currency-monitor-network

networks:
  currency-monitor-network:
    driver: bridge
