// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/currency/proto/rate.proto

package currency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RateService_GetByNameAndDate_FullMethodName      = "/proto.currency.rules.RateService/GetByNameAndDate"
	RateService_GetByNameAndDateRange_FullMethodName = "/proto.currency.rules.RateService/GetByNameAndDateRange"
)

// RateServiceClient is the client API for RateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateServiceClient interface {
	GetByNameAndDate(ctx context.Context, in *GetByNameAndDateRequest, opts ...grpc.CallOption) (*GetByNameAndDateResponse, error)
	GetByNameAndDateRange(ctx context.Context, in *GetByNameAndDateRangeRequest, opts ...grpc.CallOption) (*GetByNameAndDateRangeResponse, error)
}

type rateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRateServiceClient(cc grpc.ClientConnInterface) RateServiceClient {
	return &rateServiceClient{cc}
}

func (c *rateServiceClient) GetByNameAndDate(ctx context.Context, in *GetByNameAndDateRequest, opts ...grpc.CallOption) (*GetByNameAndDateResponse, error) {
	out := new(GetByNameAndDateResponse)
	err := c.cc.Invoke(ctx, RateService_GetByNameAndDate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateServiceClient) GetByNameAndDateRange(ctx context.Context, in *GetByNameAndDateRangeRequest, opts ...grpc.CallOption) (*GetByNameAndDateRangeResponse, error) {
	out := new(GetByNameAndDateRangeResponse)
	err := c.cc.Invoke(ctx, RateService_GetByNameAndDateRange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateServiceServer is the server API for RateService service.
// All implementations must embed UnimplementedRateServiceServer
// for forward compatibility
type RateServiceServer interface {
	GetByNameAndDate(context.Context, *GetByNameAndDateRequest) (*GetByNameAndDateResponse, error)
	GetByNameAndDateRange(context.Context, *GetByNameAndDateRangeRequest) (*GetByNameAndDateRangeResponse, error)
	mustEmbedUnimplementedRateServiceServer()
}

// UnimplementedRateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRateServiceServer struct {
}

func (UnimplementedRateServiceServer) GetByNameAndDate(context.Context, *GetByNameAndDateRequest) (*GetByNameAndDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByNameAndDate not implemented")
}
func (UnimplementedRateServiceServer) GetByNameAndDateRange(context.Context, *GetByNameAndDateRangeRequest) (*GetByNameAndDateRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByNameAndDateRange not implemented")
}
func (UnimplementedRateServiceServer) mustEmbedUnimplementedRateServiceServer() {}

// UnsafeRateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateServiceServer will
// result in compilation errors.
type UnsafeRateServiceServer interface {
	mustEmbedUnimplementedRateServiceServer()
}

func RegisterRateServiceServer(s grpc.ServiceRegistrar, srv RateServiceServer) {
	s.RegisterService(&RateService_ServiceDesc, srv)
}

func _RateService_GetByNameAndDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByNameAndDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateServiceServer).GetByNameAndDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateService_GetByNameAndDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateServiceServer).GetByNameAndDate(ctx, req.(*GetByNameAndDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateService_GetByNameAndDateRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByNameAndDateRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateServiceServer).GetByNameAndDateRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateService_GetByNameAndDateRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateServiceServer).GetByNameAndDateRange(ctx, req.(*GetByNameAndDateRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RateService_ServiceDesc is the grpc.ServiceDesc for RateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.currency.rules.RateService",
	HandlerType: (*RateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByNameAndDate",
			Handler:    _RateService_GetByNameAndDate_Handler,
		},
		{
			MethodName: "GetByNameAndDateRange",
			Handler:    _RateService_GetByNameAndDateRange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/currency/proto/rate.proto",
}
