name: Master CI

on:
  push:
    branches: [master]

jobs:

  Lint-Currency:
    name: Run lint – Currency
    runs-on: ubuntu-latest
    steps:
      - name: Pull project
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          working-directory: services/currency
          args: --timeout=3m

  Lint-Gateway:
    name: Run lint – Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Pull project
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          working-directory: services/gateway
          args: --timeout=3m
